# Generated by Django 5.0.5 on 2024-05-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
