# Generated by Django 5.0.1 on 2024-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_followuser_likepost'),
        ('testapp', '0006_alter_user_profile_profile_picture'),
    ]

    operations = [
    ]
