# Generated by Django 5.0.5 on 2024-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_user_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
