# Generated by Django 5.0.1 on 2024-05-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_post_liked'),
        ('testapp', '0011_remove_post_comments_alter_commentpost_post'),
    ]

    operations = [
    ]
